In [41]:
import pandas as pd
import numpy as np

In [42]:
df= pd.read_csv(r"netflix_titles.csv")

In [43]:
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [44]:
df.shape

(8807, 12)

In [45]:
df.columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description'],
      dtype='object')

In [46]:
df.describe()

       release_year
count   8807.000000
mean    2014.180198
std        8.819312
min     1925.000000
25%     2013.000000
50%     2017.000000
75%     2019.000000
max     2021.000000

In [47]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      6173 non-null   object
 4   cast          7982 non-null   object
 5   country       7976 non-null   object
 6   date_added    8797 non-null   object
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   object
 9   duration      8804 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: int64(1), object(11)
memory usage: 825.8+ KB

In [48]:
df['type'].value_counts()

type
Movie      6131
TV Show    2676
Name: count, dtype: int64

In [49]:
df.isnull().sum()

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

In [50]:
df['country'].nunique()

748

In [51]:
df['rating'].value_counts().head(10)

rating
TV-MA    3207
TV-14    2160
TV-PG     863
R         799
PG-13     490
TV-Y7     334
TV-Y      307
PG        287
TV-G      220
NR         80
Name: count, dtype: int64

In [52]:
df['rating'].nunique()

17

In [53]:
df[df['release_year']>2015].shape[0]

5656

In [54]:
df['country'].value_counts().head()

country
United States     2818
India              972
United Kingdom     419
Japan              245
South Korea        199
Name: count, dtype: int64

In [55]:
movies=df[df['type']=='Movie']
movies['country'].value_counts().head()

country
United States     2058
India              893
United Kingdom     206
Canada             122
Spain               97
Name: count, dtype: int64

In [56]:
tv_shows=df[df['type']=='TV Show']
tv_shows['country'].value_counts()

country
United States                                    760
United Kingdom                                   213
Japan                                            169
South Korea                                      158
India                                             79
                                                ...
Belarus                                            1
United Kingdom, Australia                          1
France, Australia, Germany                         1
Australia, New Zealand, United States              1
United States, France, South Korea, Indonesia      1
Name: count, Length: 196, dtype: int64

In [57]:
df['director'].value_counts().head()

director
Rajiv Chilaka             19
Raúl Campos, Jan Suter    18
Marcus Raboy              16
Suhas Kadav               16
Jay Karas                 14
Name: count, dtype: int64

In [58]:
movies['rating'].value_counts().head()

rating
TV-MA    2062
TV-14    1427
R         797
TV-PG     540
PG-13     490
Name: count, dtype: int64

In [59]:
tv_shows['rating'].value_counts()

rating
TV-MA       1145
TV-14        733
TV-PG        323
TV-Y7        195
TV-Y         176
TV-G          94
NR             5
R              2
TV-Y7-FV       1
Name: count, dtype: int64

In [60]:

movies['duration_min']=movies['duration'].str.extract('(\d+)').astype(float)
movies['duration_min'].mean()

C:\Users\HP\AppData\Local\Temp\ipykernel_118640\990544899.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['duration_min']=movies['duration'].str.extract('(\d+)').astype(float)

np.float64(99.57718668407311)

In [61]:
df['release_year'].value_counts().head()

release_year
2018    1147
2017    1032
2019    1030
2020     953
2016     902
Name: count, dtype: int64

In [62]:

df['date_added'].value_counts().head()

date_added
January 1, 2020      109
November 1, 2019      89
March 1, 2018         75
December 31, 2019     74
October 1, 2018       71
Name: count, dtype: int64

In [63]:
df['date_added']=pd.to_datetime(df['date_added'],errors='coerce')
df['year_added']=df['date_added'].dt.year
df['month_added']=df['date_added'].dt.month

In [64]:
tv=df[df['type']=='TV Show'].copy()
tv['seasons']=tv['duration'].str.extract('(\d+)').astype(float)
tv[['duration','seasons']].head()

    duration  seasons
1  2 Seasons      2.0
2   1 Season      1.0
3   1 Season      1.0
4  2 Seasons      2.0
5   1 Season      1.0

In [65]:
df['type'].value_counts()

type
Movie      6131
TV Show    2676
Name: count, dtype: int64

In [66]:
df['type'].unique()

array(['Movie', 'TV Show'], dtype=object)

In [67]:
current_year=pd.Timestamp.now().year
df['content_age']=current_year-df['release_year']
df['content_age'].head(10)

0     6
1     5
2     5
3     5
4     5
5     5
6     5
7    33
8     5
9     5
Name: content_age, dtype: int64

In [108]:
df['listed_in'].str.split(', ').explode().value_counts()

listed_in
International Movies            2752
Dramas                          2427
Comedies                        1674
International TV Shows          1351
Documentaries                    869
Action & Adventure               859
TV Dramas                        763
Independent Movies               756
Children & Family Movies         641
Romantic Movies                  616
TV Comedies                      581
Thrillers                        577
Crime TV Shows                   470
Kids' TV                         451
Docuseries                       395
Music & Musicals                 375
Romantic TV Shows                370
Horror Movies                    357
Stand-Up Comedy                  343
Reality TV                       255
British TV Shows                 253
Sci-Fi & Fantasy                 243
Sports Movies                    219
Anime Series                     176
Spanish-Language TV Shows        174
TV Action & Adventure            168
Korean TV Shows                  151
Classic Movies                   116
LGBTQ Movies                     102
TV Mysteries                      98
Science & Nature TV               92
TV Sci-Fi & Fantasy               84
TV Horror                         75
Anime Features                    71
Cult Movies                       71
Teen TV Shows                     69
Faith & Spirituality              65
TV Thrillers                      57
Movies                            57
Stand-Up Comedy & Talk Shows      56
Classic & Cult TV                 28
TV Shows                          16
Name: count, dtype: int64

In [69]:
df_exploded = df.copy()
df_exploded['genre'] = df_exploded['listed_in'].str.split(', ')
df_exploded = df_exploded.explode('genre')
df_2018 = df_exploded[df_exploded['release_year'] >= 2018].copy()
df_2018['genre'].value_counts().head(10)

genre
International Movies        1002
Dramas                       834
International TV Shows       754
Comedies                     540
TV Dramas                    452
Documentaries                354
TV Comedies                  334
Crime TV Shows               305
Children & Family Movies     274
Independent Movies           269
Name: count, dtype: int64

In [70]:
df_exploded['release_year'].dtype

dtype('int64')

In [71]:
df_exploded=df.copy()
df_exploded['genre']=df_exploded['listed_in'].str.split(', ')
df_exploded=df_exploded.explode('genre')
df_exploded.groupby(['type','genre']).size().sort_values(ascending=False)

type     genre
Movie    International Movies            2752
         Dramas                          2427
         Comedies                        1674
TV Show  International TV Shows          1351
Movie    Documentaries                    869
         Action & Adventure               859
TV Show  TV Dramas                        763
Movie    Independent Movies               756
         Children & Family Movies         641
         Romantic Movies                  616
TV Show  TV Comedies                      581
Movie    Thrillers                        577
TV Show  Crime TV Shows                   470
         Kids' TV                         451
         Docuseries                       395
Movie    Music & Musicals                 375
TV Show  Romantic TV Shows                370
Movie    Horror Movies                    357
         Stand-Up Comedy                  343
TV Show  Reality TV                       255
         British TV Shows                 253
Movie    Sci-Fi & Fantasy                 243
         Sports Movies                    219
TV Show  Anime Series                     176
         Spanish-Language TV Shows        174
         TV Action & Adventure            168
         Korean TV Shows                  151
Movie    Classic Movies                   116
         LGBTQ Movies                     102
TV Show  TV Mysteries                      98
         Science & Nature TV               92
         TV Sci-Fi & Fantasy               84
         TV Horror                         75
Movie    Cult Movies                       71
         Anime Features                    71
TV Show  Teen TV Shows                     69
Movie    Faith & Spirituality              65
         Movies                            57
TV Show  TV Thrillers                      57
         Stand-Up Comedy & Talk Shows      56
         Classic & Cult TV                 28
         TV Shows                          16
dtype: int64

In [72]:
df_exploded=df.copy()
df_exploded['genre']=df_exploded['listed_in'].str.split(', ')
df_exploded=df_exploded.explode('genre')
df_exploded['country']=df_exploded['country'].str.split(', ')
df_exploded=df_exploded.explode('country')
df_exploded.groupby(['country','genre']).size().sort_values(ascending=False).head(20)

country         genre
India           International Movies        864
United States   Dramas                      835
                Comedies                    680
India           Dramas                      662
United States   Documentaries               511
                Action & Adventure          404
                Independent Movies          390
                Children & Family Movies    390
India           Comedies                    323
United States   Thrillers                   292
                TV Comedies                 258
                TV Dramas                   232
                Romantic Movies             225
United Kingdom  British TV Shows            225
United States   Stand-Up Comedy             216
                Kids' TV                    214
France          International Movies        207
United States   Horror Movies               201
United Kingdom  Dramas                      196
United States   Docuseries                  192
dtype: int64

In [73]:
movies['duration_min']=movies['duration'].str.extract('(\d+)').astype(float)
longest=movies.loc[movies['duration_min'].idxmax()][['title', 'duration_min','country']]
print(longest)

title           Black Mirror: Bandersnatch
duration_min                         312.0
country                      United States
Name: 4253, dtype: object

C:\Users\HP\AppData\Local\Temp\ipykernel_118640\193953702.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['duration_min']=movies['duration'].str.extract('(\d+)').astype(float)

In [74]:
movies['duration_min']=movies['duration'].str.extract('(\d+)').astype(float)
longest=movies.loc[movies['duration_min'].idxmin()][['title', 'duration_min']]
print(longest)

title           Silent
duration_min       3.0
Name: 3777, dtype: object

C:\Users\HP\AppData\Local\Temp\ipykernel_118640\3158591360.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['duration_min']=movies['duration'].str.extract('(\d+)').astype(float)

In [75]:
df['date_added']=pd.to_datetime(df['date_added'],errors='coerce')
df['month_added']=df['date_added'].dt.month
df['month_added'].value_counts().sort_index()

month_added
1.0     727
2.0     557
3.0     734
4.0     759
5.0     626
6.0     724
7.0     819
8.0     749
9.0     765
10.0    755
11.0    697
12.0    797
Name: count, dtype: int64

In [76]:
df['date_added'].dt.year.value_counts().sort_index()

date_added
2008.0       2
2009.0       2
2010.0       1
2011.0      13
2012.0       3
2013.0      10
2014.0      23
2015.0      73
2016.0     418
2017.0    1164
2018.0    1625
2019.0    1999
2020.0    1878
2021.0    1498
Name: count, dtype: int64

In [77]:
df['release_year'].value_counts().sort_index().tail(20)

release_year
2002      51
2003      61
2004      64
2005      80
2006      96
2007      88
2008     136
2009     152
2010     194
2011     185
2012     237
2013     288
2014     352
2015     560
2016     902
2017    1032
2018    1147
2019    1030
2020     953
2021     592
Name: count, dtype: int64

In [78]:
df['year_added'] = df['date_added'].dt.year

df.groupby(['year_added', 'type']).size().unstack().fillna(0)

type         Movie  TV Show
year_added
2008.0         1.0      1.0
2009.0         2.0      0.0
2010.0         1.0      0.0
2011.0        13.0      0.0
2012.0         3.0      0.0
2013.0         6.0      4.0
2014.0        19.0      4.0
2015.0        56.0     17.0
2016.0       253.0    165.0
2017.0       839.0    325.0
2018.0      1237.0    388.0
2019.0      1424.0    575.0
2020.0      1284.0    594.0
2021.0       993.0    505.0

In [81]:
df['country'].str.split('(\d+)').explode().value_counts().head(10)

country
United States     2818
India              972
United Kingdom     419
Japan              245
South Korea        199
Canada             181
Spain              145
France             124
Mexico             110
Egypt              106
Name: count, dtype: int64

In [83]:
movies=df[df['type']=='Movie']
movies['country'].str.split('(\d)').explode().value_counts().head(10)

country
United States     2058
India              893
United Kingdom     206
Canada             122
Spain               97
Egypt               92
Nigeria             86
Indonesia           77
Turkey              76
Japan               76
Name: count, dtype: int64

In [91]:
result=df.explode('country').groupby(['country','type']).size().unstack().fillna(0)
result['total']=result['Movie']+result['TV Show']
result.sort_values(by=['total'],ascending=False).head(10)

type             Movie  TV Show   total
country
United States   2058.0    760.0  2818.0
India            893.0     79.0   972.0
United Kingdom   206.0    213.0   419.0
Japan             76.0    169.0   245.0
South Korea       41.0    158.0   199.0
Canada           122.0     59.0   181.0
Spain             97.0     48.0   145.0
France            75.0     49.0   124.0
Mexico            70.0     40.0   110.0
Egypt             92.0     14.0   106.0

In [96]:
df['director'].str.split(', ').explode().dropna().value_counts().head(10)

director
Rajiv Chilaka          22
Jan Suter              21
Raúl Campos            19
Suhas Kadav            16
Marcus Raboy           16
Jay Karas              15
Cathy Garcia-Molina    13
Jay Chapman            12
Youssef Chahine        12
Martin Scorsese        12
Name: count, dtype: int64

In [97]:
df['cast'].str.split(', ').explode().dropna().value_counts().head(10)

cast
Anupam Kher         43
Shah Rukh Khan      35
Julie Tejwani       33
Naseeruddin Shah    32
Takahiro Sakurai    32
Rupa Bhimani        31
Akshay Kumar        30
Om Puri             30
Yuki Kaji           29
Paresh Rawal        28
Name: count, dtype: int64

In [101]:
df.groupby('release_year').size().tail(10)

release_year
2012     237
2013     288
2014     352
2015     560
2016     902
2017    1032
2018    1147
2019    1030
2020     953
2021     592
dtype: int64

In [105]:
df['release_year'].value_counts().sort_values(ascending=False)

release_year
2018    1147
2017    1032
2019    1030
2020     953
2016     902
        ...
1959       1
1925       1
1961       1
1947       1
1966       1
Name: count, Length: 74, dtype: int64

In [107]:
df['date_added']=pd.to_datetime(df['date_added'])
df['month']=df['date_added'].dt.month
df['month'].value_counts().sort_values(ascending=False)

month
7.0     819
12.0    797
9.0     765
4.0     759
10.0    755
8.0     749
3.0     734
1.0     727
6.0     724
11.0    697
5.0     626
2.0     557
Name: count, dtype: int64

In [113]:
movies=df[df['type']=='Movie'].copy()
movies['duration_min']=movies['duration'].str.extract('(\d+)').astype(float)
movies['duration_min'].describe()

count    6128.000000
mean       99.577187
std        28.290593
min         3.000000
25%        87.000000
50%        98.000000
75%       114.000000
max       312.000000
Name: duration_min, dtype: float64

In [115]:
tv=df[df['type']=='TV Show'].copy()
tv['season']=tv['duration'].str.extract('(\d+)').astype(float)
tv['season'].describe()

count    2676.000000
mean        1.764948
std         1.582752
min         1.000000
25%         1.000000
50%         1.000000
75%         2.000000
max        17.000000
Name: season, dtype: float64

In [121]:
movies=df[df['type']=='Movie'].copy()
movies['duration_min']=movies['duration'].str.extract('(\d+)').astype(float)
movies['country'].str.split(', ').explode().dropna().head(10)
movies.groupby(['country'])['duration_min'].mean().sort_values(ascending=False).head(10)

country
United Kingdom, United States, Japan                   208.0
United States, United Kingdom, Morocco                 205.0
United States, Italy, United Kingdom, Liechtenstein    200.0
New Zealand, United States                             190.0
Romania, France, Switzerland, Germany                  186.0
France, Belgium, Spain                                 180.0
Germany, United States, Hong Kong, Singapore           172.0
India, Soviet Union                                    161.5
United Kingdom, United States, Morocco                 161.0
India, United Kingdom                                  160.0
Name: duration_min, dtype: float64

In [122]:
df.groupby(['release_year','type']).size().unstack().fillna(0)

type          Movie  TV Show
release_year
1925            0.0      1.0
1942            2.0      0.0
1943            3.0      0.0
1944            3.0      0.0
1945            3.0      1.0
...             ...      ...
2017          767.0    265.0
2018          767.0    380.0
2019          633.0    397.0
2020          517.0    436.0
2021          277.0    315.0

[74 rows x 2 columns]

In [148]:
(df['type'].value_counts(normalize=True)*100).round(2).head()

type
Movie      69.62
TV Show    30.38
Name: proportion, dtype: float64

In [168]:
movies=df[df['type']=='Movie'].copy()
movies['duration_min']=movies['duration'].str.extract('(\d+)').astype(float)
movies.groupby(['rating'])['duration_min'].mean().sort_values(ascending=False)

rating
NC-17       125.000000
TV-14       110.290820
PG-13       108.330612
R           106.720201
UR          106.333333
PG           98.282230
TV-MA        95.889913
TV-PG        94.851852
NR           94.533333
G            90.268293
TV-G         79.666667
TV-Y7-FV     68.400000
TV-Y7        66.287770
TV-Y         48.114504
66 min             NaN
74 min             NaN
84 min             NaN
Name: duration_min, dtype: float64